-   id: bazelisk-buildifier
    name: 'bazelisk buildifier'
    entry: run-bazelisk-buildifier.sh
    files: 'BUILD.bazel|BUILD'
    language: 'script'
    description: "Runs `buildifier` with bazelisk"
